image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - bundle install
  - apt-get update
  - apt-get install -y zip
  - zip -FS9ryo dist/jekyll-starter-kit.zip . -x .\* -x Gemfile.lock -x .gitlab-ci.yml -x .git -x dist/\*

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  except:
    - master

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master
