title: Gommat
description: A minimal blog

baseurl: /gommat

include:
  - _pages

# sass configuration
sass:
  sass_dir: /assets/css/_sass
  style: compressed

# jekyll collections
collections:
  stamps:
    output: true
    permalink: /stamps/:path/

# Color scheme
primary: "#907be4 !default"
secondary: "#6c757d !default"
success: "#28a745 !default"
info: "#17a2b8 !default"
warning: "#ffc107 !default"
danger: "#dc3545 !default"
light: "#f8f9fa !default"
dark: "#343a40 !default"

# jekyll plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
